### ISSUE TITLE
Text style and layer Style

### ISSUE THREAD

**Issue by leolav** [Pausansol/Camilo#2]
Hello, Thank you very much for your job, it's amazing.

I work on sketch 52.4 and text and layer style doesn't change, only symbols.

**Comment by Pausansol** [comment]
Hi, I tested it in 52.4 and working as expected.
To change text and layer styles, they have to be Shared Styles in both documents, with same names. 
Then, Camilo will replace them. You can find example files to test how it works [here](https://github.com/Pausansol/Camilo/releases/download/1.0/Example.zip).

Cheers

**Comment by lvcs** [comment]
I'm experiencing the same issue as @leolav, tested with the attached example files

**Comment by Pausansol** [comment]
Did you follow the next steps?

1 - Install the brand libraries
2 - Open uiKit file
3 - Press Control + Command + C or use the Plugins menu and choose brand_2 (uiKit comes with brand_1 styles applied)

**Comment by lvcs** [comment]
Yes, how would you use text and layer style in a brand new file?

**Comment by Pausansol** [comment]
I'm not sure if I'm understanding the issue. Can you give me more details? 

@lvcs for a brand new file you have to set the local layer and text styles with the same name as they are in libraries to do the swap. We are developing a new feature with override styles from a library instead of local styles, which is more appropriate since it provides the capacity to update the libraries.
